FROM balenalib/raspberry-pi-python

RUN [ "cross-build-start" ]

WORKDIR /usr/src/app

RUN apt update
RUN apt-get install python3 -y
RUN apt-get install python3-pip -y
RUN apt-get install python3-pil -y
RUN apt-get install rpi.gpio -y
RUN pip3 install adafruit-circuitpython-ssd1306

COPY . .

CMD modprobe i2c-dev && python3 stats.py

RUN [ "cross-build-end" ]